import type { DemoAiKnowledgeEntry, DemoAiLink } from './demoAiTypes';

export const DEMO_AI_AGENT_NAME = 'ORDERra Support Agent';

export const DEMO_AI_HELP_CENTER_LINK: DemoAiLink = {
  label: 'Help Center',
  path: '/help-center',
};

export const DEMO_AI_PRIVACY_POLICY_LINK: DemoAiLink = {
  label: 'Privacy Policy',
  path: '/privacy-policy',
};

export const DEMO_AI_WELCOME =
  'Hi, I’m ORDERra Support Agent. I can help with ordering, delivery, pickup, dine-in, payment demo, refunds, privacy, and support topics.';

export const DEMO_AI_DEFAULT_QUICK_REPLIES = [
  'What is ORDERra?',
  'How payment works?',
  'Delivery tracking',
  'Dine-in QR',
] as const;

export const DEMO_AI_SUPPORT_FALLBACK =
  'I can help with ORDERra ordering, delivery, pickup, dine-in, payment demo, refunds, privacy, and support topics. Please choose one of the suggested topics below.';

export const DEMO_AI_KNOWLEDGE_BASE: DemoAiKnowledgeEntry[] = [
  {
    id: 'about-orderra',
    topic: 'getting_started',
    question: 'What is ORDERra?',
    answer:
      'ORDERra is a premium burger ordering demo for one restaurant. You can explore the menu, cart, checkout, and order tracking flow without placing a real order.',
    keywords: [
      'what is orderra',
      'about orderra',
      'is orderra real',
      'real restaurant',
      'demo app',
      'portfolio',
      'burger ordering',
    ],
    quickReplies: ['Can I place a real order?', 'How payment works?', 'Delivery tracking'],
    helpCenterCategory: 'getting_started',
  },
  {
    id: 'real-order-boundary',
    topic: 'getting_started',
    question: 'Can I place a real order?',
    answer:
      'No. ORDERra is a safe portfolio demo, so nothing is sent to a real kitchen, rider, restaurant team, or payment service.',
    keywords: [
      'real order',
      'place real order',
      'order food',
      'actual order',
      'kitchen',
      'restaurant team',
      'real restaurant',
    ],
    quickReplies: ['Delivery tracking', 'Pickup', 'Dine-in QR'],
    links: [DEMO_AI_HELP_CENTER_LINK],
    helpCenterCategory: 'getting_started',
  },
  {
    id: 'menu-browsing',
    topic: 'menu_customization',
    question: 'How do I browse the menu?',
    answer:
      'You can browse burgers, combos, sides, desserts, and drinks from the menu sections. Add anything you like to the cart and review it before checkout.',
    keywords: [
      'browse menu',
      'menu',
      'category',
      'categories',
      'search menu',
      'food item',
      'items',
      'combo',
      'dessert',
      'drinks',
    ],
    quickReplies: ['Best burger?', 'See drinks', 'Combo meals'],
    helpCenterCategory: 'menu_customization',
  },
  {
    id: 'menu-customization',
    topic: 'menu_customization',
    question: 'Can I customize my order?',
    answer:
      'Some items include demo variants, add-ons, and notes. Any note you enter stays inside the demo and is not sent to a real restaurant.',
    keywords: [
      'customize',
      'modifier',
      'add on',
      'addon',
      'variant',
      'remove ingredient',
      'special note',
      'allergy note',
      'custom order',
    ],
    quickReplies: ['Cart and checkout', 'How payment works?', 'Privacy'],
    helpCenterCategory: 'menu_customization',
  },
  {
    id: 'cart-checkout',
    topic: 'cart_checkout',
    question: 'How does checkout work?',
    answer:
      'Add items to the cart, choose delivery, pickup, or dine-in, then review the demo total before placing the order. The checkout feels realistic, but no real transaction is created.',
    keywords: [
      'checkout',
      'cart',
      'basket',
      'place order',
      'submit order',
      'review order',
      'totals',
      'total',
      'fees',
    ],
    quickReplies: ['How payment works?', 'Delivery tracking', 'Pickup'],
    links: [DEMO_AI_HELP_CENTER_LINK],
    helpCenterCategory: 'cart_checkout',
  },
  {
    id: 'payment-simulation',
    topic: 'payment_simulation',
    question: 'How payment works?',
    answer:
      'Payments in ORDERra are for safe demo testing only. You can try the checkout experience, but no real card, wallet, bank, or PayPal payment will be charged.',
    keywords: [
      'payment',
      'pay',
      'card',
      'credit card',
      'debit card',
      'wallet',
      'apple pay',
      'google pay',
      'paypal',
      'ach',
      'cash',
      'charge',
      'charged',
    ],
    quickReplies: ['Will my card be charged?', 'Refund demo', 'Privacy'],
    links: [DEMO_AI_PRIVACY_POLICY_LINK, DEMO_AI_HELP_CENTER_LINK],
    helpCenterCategory: 'payment_simulation',
  },
  {
    id: 'payment-safety',
    topic: 'payment_simulation',
    question: 'Will my card be charged?',
    answer:
      'No. ORDERra does not collect real card details and will not charge your card, wallet, bank, or PayPal account in this demo.',
    keywords: [
      'will my card be charged',
      'card charged',
      'real card',
      'card data',
      'payment capture',
      'live payment',
      'money',
      'bank',
      'paypal charge',
      'wallet charge',
    ],
    quickReplies: ['How payment works?', 'Refund demo', 'Privacy Policy'],
    links: [DEMO_AI_PRIVACY_POLICY_LINK],
    helpCenterCategory: 'payment_simulation',
  },
  {
    id: 'delivery-tracking',
    topic: 'delivery_tracking',
    question: 'Delivery tracking',
    answer:
      'Delivery tracking shows a realistic demo timeline with rider and ETA updates. No real rider is assigned and no real delivery is created.',
    keywords: [
      'delivery',
      'tracking',
      'track',
      'rider',
      'driver',
      'eta',
      'dispatch',
      'near customer',
      'delivered',
      'where is my order',
    ],
    quickReplies: ['Pickup', 'Order status', 'Refund demo'],
    links: [DEMO_AI_HELP_CENTER_LINK],
    helpCenterCategory: 'delivery_tracking',
  },
  {
    id: 'pickup-flow',
    topic: 'pickup',
    question: 'Pickup',
    answer:
      'You can test the pickup flow before checkout. It shows how a ready-for-pickup order could work, but no real counter receives the order.',
    keywords: [
      'pickup',
      'pick up',
      'collect',
      'ready for pickup',
      'counter',
      'pickup time',
      'self pickup',
    ],
    quickReplies: ['Cart and checkout', 'Order status', 'How payment works?'],
    links: [DEMO_AI_HELP_CENTER_LINK],
    helpCenterCategory: 'pickup',
  },
  {
    id: 'dine-in-qr',
    topic: 'dine_in_qr',
    question: 'Dine-in QR',
    answer:
      'You can try dine-in QR ordering through a demo table session. Add items, review the order, and test checkout without contacting a real waiter.',
    keywords: [
      'dine-in',
      'dine in',
      'qr',
      'table',
      'table session',
      'scan',
      'waiter',
      'pay at table',
      'table order',
    ],
    quickReplies: ['Split bill', 'How payment works?', 'Request bill'],
    links: [DEMO_AI_HELP_CENTER_LINK],
    helpCenterCategory: 'dine_in_qr',
  },
  {
    id: 'split-bill',
    topic: 'dine_in_qr',
    question: 'Split bill',
    answer:
      'Split bill is available as a dine-in demo feature. You can test equal split or item-based split without creating a real payment request.',
    keywords: [
      'split bill',
      'split payment',
      'equal split',
      'split by item',
      'participants',
      'share bill',
      'pay separately',
    ],
    quickReplies: ['Dine-in QR', 'How payment works?', 'Help Center'],
    links: [DEMO_AI_HELP_CENTER_LINK],
    helpCenterCategory: 'dine_in_qr',
  },
  {
    id: 'request-bill',
    topic: 'dine_in_qr',
    question: 'Request bill',
    answer:
      'The request bill flow is included for dine-in demo testing. It shows how a table could review the bill before payment, without calling a real waiter.',
    keywords: [
      'request bill',
      'bill requested',
      'ask for bill',
      'pay bill',
      'table bill',
      'dine in bill',
    ],
    quickReplies: ['Split bill', 'Dine-in QR', 'How payment works?'],
    links: [DEMO_AI_HELP_CENTER_LINK],
    helpCenterCategory: 'dine_in_qr',
  },
  {
    id: 'order-status',
    topic: 'cart_checkout',
    question: 'Order status',
    answer:
      'ORDERra shows demo order states like placed, preparing, ready, delivered, and completed. These updates help visitors understand how a real ordering system could feel.',
    keywords: [
      'order status',
      'status',
      'placed',
      'confirmed',
      'preparing',
      'ready',
      'completed',
      'timeline',
      'order timeline',
    ],
    quickReplies: ['Delivery tracking', 'Pickup', 'Refund demo'],
    links: [DEMO_AI_HELP_CENTER_LINK],
    helpCenterCategory: 'cart_checkout',
  },
  {
    id: 'refund-demo',
    topic: 'refunds_issues',
    question: 'Refund demo',
    answer:
      'Refunds are shown as demo examples only. They help visitors understand refund states without sending money back through a real payment service.',
    keywords: [
      'refund',
      'cancel',
      'cancellation',
      'missing item',
      'wrong item',
      'late delivery',
      'partial refund',
      'store credit',
      'money back',
    ],
    quickReplies: ['How payment works?', 'Support demo', 'Help Center'],
    links: [DEMO_AI_HELP_CENTER_LINK],
    helpCenterCategory: 'refunds_issues',
  },
  {
    id: 'promo-demo',
    topic: 'cart_checkout',
    question: 'Promo codes',
    answer:
      'Promo codes are included to demonstrate checkout discounts. They are demo-only and are not connected to a real restaurant campaign.',
    keywords: ['promo', 'promo code', 'coupon', 'discount', 'WELCOME10', 'COMBO5', 'voucher'],
    quickReplies: ['Cart and checkout', 'How payment works?', 'Help Center'],
    helpCenterCategory: 'cart_checkout',
  },
  {
    id: 'privacy-storage',
    topic: 'account_privacy',
    question: 'Privacy',
    answer:
      'ORDERra may remember demo cart, account, and support chat activity in your browser. Please do not enter sensitive personal or payment details in this demo.',
    keywords: [
      'privacy',
      'data',
      'personal data',
      'localStorage',
      'local storage',
      'cookies',
      'browser storage',
      'sensitive',
      'stored data',
    ],
    quickReplies: ['Privacy Policy', 'How payment works?', 'Support demo'],
    links: [DEMO_AI_PRIVACY_POLICY_LINK],
    helpCenterCategory: 'account_privacy',
  },
  {
    id: 'account-login-demo',
    topic: 'account_privacy',
    question: 'Account and login',
    answer:
      'Account and login screens are included to make the demo feel realistic. Please treat them as demo account screens, not a real customer account.',
    keywords: [
      'account',
      'login',
      'sign in',
      'signin',
      'register',
      'profile',
      'password',
      'customer account',
    ],
    quickReplies: ['Privacy', 'Help Center', 'Can I place a real order?'],
    links: [DEMO_AI_PRIVACY_POLICY_LINK, DEMO_AI_HELP_CENTER_LINK],
    helpCenterCategory: 'account_privacy',
  },
  {
    id: 'human-support-boundary',
    topic: 'support_demo',
    question: 'Can I talk to a human agent?',
    answer:
      'This is a demo support agent, so it does not contact a real human agent or create a real support ticket. You can still use the Help Center for detailed demo guidance.',
    keywords: [
      'human agent',
      'real person',
      'talk to staff',
      'talk to support',
      'talk to agent',
      'live agent',
      'live chat',
      'contact support',
      'customer service',
      'support ticket',
      'create ticket',
      'request demo help',
      'need more help',
      'talk with someone',
    ],
    quickReplies: ['Help Center', 'Privacy Policy', 'Refund demo'],
    links: [DEMO_AI_HELP_CENTER_LINK, DEMO_AI_PRIVACY_POLICY_LINK],
    helpCenterCategory: 'support_demo',
  },
  {
    id: 'support-demo',
    topic: 'support_demo',
    question: 'Support demo',
    answer:
      'This support agent uses approved demo answers only. It can guide you through ORDERra topics, but it does not connect to a real support team.',
    keywords: [
      'support demo',
      'support',
      'agent',
      'ai',
      'assistant',
      'support boundary',
      'chat support',
      'support help',
    ],
    quickReplies: ['Help Center', 'Privacy Policy', 'Refund demo'],
    links: [DEMO_AI_HELP_CENTER_LINK, DEMO_AI_PRIVACY_POLICY_LINK],
    helpCenterCategory: 'support_demo',
  },
  {
    id: 'help-center-link',
    topic: 'support_demo',
    question: 'Help Center',
    answer:
      'You can open the Help Center for deeper details about ordering, delivery, pickup, dine-in, payments, refunds, privacy, and support.',
    keywords: [
      'help center',
      'faq',
      'questions',
      'more details',
      'learn more',
      '/help',
      '/help-center',
      'guide',
    ],
    quickReplies: ['Privacy Policy', 'How payment works?', 'Dine-in QR'],
    links: [DEMO_AI_HELP_CENTER_LINK],
    helpCenterCategory: 'support_demo',
  },
  {
    id: 'privacy-policy-link',
    topic: 'account_privacy',
    question: 'Privacy Policy',
    answer:
      'The Privacy Policy explains demo data, browser storage, payment safety, support boundaries, and retention notes.',
    keywords: [
      'privacy policy',
      'policy',
      '/privacy',
      '/privacy-policy',
      'data policy',
      'retention',
      'privacy page',
    ],
    quickReplies: ['Privacy', 'Support demo', 'Help Center'],
    links: [DEMO_AI_PRIVACY_POLICY_LINK],
    helpCenterCategory: 'account_privacy',
  },
];
